/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/$workspaceSlug/index'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/$workspaceSlug/settings'
import { Route as WorkspaceSlugProjectIdListRouteImport } from './routes/$workspaceSlug/$projectId/list'
import { Route as WorkspaceSlugProjectIdBoardRouteImport } from './routes/$workspaceSlug/$projectId/board'
import { Route as WorkspaceSlugProjectIdIssuesIssueNumberRouteImport } from './routes/$workspaceSlug/$projectId/issues/$issueNumber'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/$workspaceSlug/',
  path: '/$workspaceSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/$workspaceSlug/settings',
  path: '/$workspaceSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugProjectIdListRoute =
  WorkspaceSlugProjectIdListRouteImport.update({
    id: '/$workspaceSlug/$projectId/list',
    path: '/$workspaceSlug/$projectId/list',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugProjectIdBoardRoute =
  WorkspaceSlugProjectIdBoardRouteImport.update({
    id: '/$workspaceSlug/$projectId/board',
    path: '/$workspaceSlug/$projectId/board',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugProjectIdIssuesIssueNumberRoute =
  WorkspaceSlugProjectIdIssuesIssueNumberRouteImport.update({
    id: '/$workspaceSlug/$projectId/issues/$issueNumber',
    path: '/$workspaceSlug/$projectId/issues/$issueNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/$projectId/board': typeof WorkspaceSlugProjectIdBoardRoute
  '/$workspaceSlug/$projectId/list': typeof WorkspaceSlugProjectIdListRoute
  '/$workspaceSlug/$projectId/issues/$issueNumber': typeof WorkspaceSlugProjectIdIssuesIssueNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/$workspaceSlug': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/$projectId/board': typeof WorkspaceSlugProjectIdBoardRoute
  '/$workspaceSlug/$projectId/list': typeof WorkspaceSlugProjectIdListRoute
  '/$workspaceSlug/$projectId/issues/$issueNumber': typeof WorkspaceSlugProjectIdIssuesIssueNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/$projectId/board': typeof WorkspaceSlugProjectIdBoardRoute
  '/$workspaceSlug/$projectId/list': typeof WorkspaceSlugProjectIdListRoute
  '/$workspaceSlug/$projectId/issues/$issueNumber': typeof WorkspaceSlugProjectIdIssuesIssueNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/$projectId/board'
    | '/$workspaceSlug/$projectId/list'
    | '/$workspaceSlug/$projectId/issues/$issueNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug'
    | '/$workspaceSlug/$projectId/board'
    | '/$workspaceSlug/$projectId/list'
    | '/$workspaceSlug/$projectId/issues/$issueNumber'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/$projectId/board'
    | '/$workspaceSlug/$projectId/list'
    | '/$workspaceSlug/$projectId/issues/$issueNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugProjectIdBoardRoute: typeof WorkspaceSlugProjectIdBoardRoute
  WorkspaceSlugProjectIdListRoute: typeof WorkspaceSlugProjectIdListRoute
  WorkspaceSlugProjectIdIssuesIssueNumberRoute: typeof WorkspaceSlugProjectIdIssuesIssueNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/': {
      id: '/$workspaceSlug/'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings': {
      id: '/$workspaceSlug/settings'
      path: '/$workspaceSlug/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/$projectId/list': {
      id: '/$workspaceSlug/$projectId/list'
      path: '/$workspaceSlug/$projectId/list'
      fullPath: '/$workspaceSlug/$projectId/list'
      preLoaderRoute: typeof WorkspaceSlugProjectIdListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/$projectId/board': {
      id: '/$workspaceSlug/$projectId/board'
      path: '/$workspaceSlug/$projectId/board'
      fullPath: '/$workspaceSlug/$projectId/board'
      preLoaderRoute: typeof WorkspaceSlugProjectIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/$projectId/issues/$issueNumber': {
      id: '/$workspaceSlug/$projectId/issues/$issueNumber'
      path: '/$workspaceSlug/$projectId/issues/$issueNumber'
      fullPath: '/$workspaceSlug/$projectId/issues/$issueNumber'
      preLoaderRoute: typeof WorkspaceSlugProjectIdIssuesIssueNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugProjectIdBoardRoute: WorkspaceSlugProjectIdBoardRoute,
  WorkspaceSlugProjectIdListRoute: WorkspaceSlugProjectIdListRoute,
  WorkspaceSlugProjectIdIssuesIssueNumberRoute:
    WorkspaceSlugProjectIdIssuesIssueNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
